### ISSUE TITLE
Fix mobile layout so that legend doesn't overlap map

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [wottomgauss/unity2020maps#2]
Here is a screenshot from Firefox on Android:

![Screenshot_20200801-155305_Firefox](https://user-images.githubusercontent.com/6536826/89111839-7c1b8e00-d40f-11ea-96fd-45ecaac81885.jpg)

How should this look different exactly in terms of the legend overlapping the map. The opacity of the data credit?

**Comment by wottomgauss** [comment]
Looks like a previous PR fixed the legend overlapping.

**Comment by JoshuaCWebDeveloper** [comment]
Okay.. looks the same on Opera and Chrome on Android. Someone may want to check Chrome and Safari on iOS.
